### PR TITLE
Dynamic recipe API

### PR DESCRIPTION
**Pull request by ZephireNZ**
This PR provides the ability for Glowstone as well as modders to create dynamic recipes. These need to access NBT or damage values, and have massive numbers of combinations - making static recipes unhelpful.

The API is purposefully quite bare compared to Shaped and Shapless recipes, so that the implementation is easy.

---

_Edited by turt2live_

**Related links:**
- Glowstone: GlowstoneMC/Glowstone#445

### CODE REVIEW

**Comment by bendem** [comment]
People coming from bukkit will be really happy about this change :O

**Comment by bendem** [comment]
```
<bendem> [...] shouldn't the result be influenced by the matrix in here https://github.com/GlowstoneMC/Glowkit/pull/34/files#diff-00a92dfb9708d83e3d47cf603d43b186R23
<@SpaceManiac> see the doc on the other method
<bendem> well, that would mean you can't add dynamic recipe from plugins, or you should find a way to make sure plugin dev actually set the matrix to use it in getResult
<bendem> aka, wouldn't it be better to have a class there instead of an interface?
<bendem> like make a class like the other which would be constructed like new DynamicRecipe(result).setMatcher(matcher) with an ItemStackMatcher interface
<bendem> that would match the current behavior of other recipes
<bendem> I should write that on the pr
```

**Comment by ZephireNZ** [comment]
@bendem: Before I go any further, care to elaborate?

**Comment by bendem** [comment]
There are 3 things bothering me in this interface.
- We keep telling plugin developers to not extend org.bukkit classes by themselves (that's supposed to be up to the implementation)
- The plugin devs will have to store the matrix themselves and I fear what they will do with that
- Other recipe are actual object they can instantiate and setup before registering and it would maybe best to follow that course of action

I thought of something like [this](https://gist.github.com/bendem/3f89d284b6009acdb17c) could maybe be a way of doing it.

EDIT: We came up with [~~this~~](https://gist.github.com/bendem/99efc2a8e1675248fc15#file-28_11-55-02-java-L63-L64)(edit: gist died) on irc, which prevents parsing the matrix once when matching and once when getting the result.

**Comment by turt2live** [comment]
Changed state to WIP because the Glowstone side is still not complete

**Comment by ZephireNZ** [comment]
Fair enough. Once I get my computer going, I think I'm going to remove the clear part for now anyway. Once the recipes are pulled, I'll work on getting _all_ crafting recipes to clear the matrix properly.

**Comment by bendem** [comment]
@ZephireNZ After seeing the implementation, I think it would make sense to let the recipe clean the matrix. Maybe something like `new DynamicRecipe(itemMatcher, itemCleaner)` where ItemCleaner is an interface like 

``` java
interface ItemCleaner {
    public ItemStack[] clean(ItemStack[]);
}
```

or just adding a new `ItemStack[] clean(ItemStack[])` method to ItemMatcher.

(I'd personally go with the first option because it would allow users to not  implement the method for the default behavior and because java 8 lambdas)

**Comment by ZephireNZ** [comment]
Like I said, I'll get these changes pulled first, then I'll work on getting the matrix to be cleaned. Currently all other recipes are also not cleaned, so I could will probably get both working in one go.

**Pull request closed without merging**
