### PR TITLE
Use world from CommandSender when setting weather, if available

### PR DESCRIPTION
**Pull request by Aaron1011**
This resolves https://github.com/GlowstoneMC/Glowstone/issues/615

Thanks to @Tonodus for finding the issue.

### CODE REVIEW

**Comment by turt2live** [comment]
Although more difficult, I'd like to see how Vanilla handles this

**Comment by Aaron1011** [comment]
This is actually _more_ sophisticated than Vanilla, which always uses the first world.

**Comment by turt2live** [comment]
Is there evidence of vanilla only ever using the first world though? (I'm just curious). 

This PR is entirely up to @SpaceManiac though.

**Comment by Aaron1011** [comment]
I determined that by looking at the implementation of the weather command. Vanilla always gets the first world it has loaded.

**Comment by turt2live** [comment]
Makes sense I suppose, multi-world isn't really in vanilla. 

I think this is a reasonable change though namely because weather can occur in other worlds.

**Comment by turt2live** [comment]
Still currently pending review from @SpaceManiac

**Comment by SpaceManiac** [comment]
Accepted, I think it's certainly better behavior to change a specific world's time than only the first world's. Probably need to look at commands on the whole at some point, though.

**Comment by SpaceManiac** [comment]
Merged in 5290c31. Thanks!

**Pull request closed without merging**
