### PR TITLE
[WIP] Fix Javadocs

### PR DESCRIPTION
**Pull request by socram8888**
Glowkit won't compile using the Javadocs executable provided with Java 8. This is a WIP PR to fix it.

### CODE REVIEW

**Comment by turt2live** [comment]
Formatting PRs are not accepted. Thank you for your efforts and they have been noted.

**Comment by socram8888** [comment]
How I'm supposed to compile this is Javadocs halts compilation process?

This is not the kind of formatting issue that makes it look bad. It's the
kind of issue that totally prevents anybody from compiling or installing
Glowkit.

**Comment by turt2live** [comment]
Glowkit compiles for Java 6. Compiling for any other version is not targeted at the moment.

**Comment by dequis** [comment]
Someone should fix it, either way. Also I think this PR was so WIP it didn't do anything interesting yet.

**Comment by turt2live** [comment]
If Glowkit starts to target a higher version of Java, then it can be considered.

**Comment by dequis** [comment]
Glowkit isn't going to target java 8 any time soon and you know it.

**Comment by socram8888** [comment]
I don't get why this is wrong. This just fixes formatting errors that
prevents compilation on Java 8. These errors a hasn't been introduced due
to some changes in JDK8, it's just that older versions don't mind compiling
invalid Javadocs code. Fixing them won't prevent you from being able to
compile using Java 6 or 7. You will be able to compile it using JDK 6 and
7, and also you would be able to compile it using the latest official
version.

Note that I'm not taking about compiling targeting Java 8. I mean compiling
with JDK 8 targeting Java 6 (ie generating bytecode for JRE 6).

**Comment by turt2live** [comment]
Formatting problems are not to be fixed through the PR system. Please discuss on IRC for more information.

**Comment by dequis** [comment]
For the record, the commit that actually fixes the formatting errors is https://github.com/socram8888/Glowkit/commit/20a8a348cf8b30ce505c6d4cc6aadb4ab21548cc

**Pull request closed without merging**
