### PR TITLE
Update magic values for Skull directions

### PR DESCRIPTION
**Pull request by Aaron1011**
East and West have switched in 1.8.

### CODE REVIEW

**Comment by ZachBora** [comment]
mojang why did you do that...

**Comment by ZachBora** [comment]
By the way, shouldn't we implement all directions skulls can have?

**Comment by Aaron1011** [comment]
@ZachBora: Actually, that will be implemented in the [`BlockState` skull](https://github.com/GlowstoneMC/Glowkit/blob/master/src/main/java/org/bukkit/block/Skull.java). This Skull is a subclass of MaterialData, which only allows setting the one byte of data.

All of the other rotations require data to be stored in the tile entity

**Comment by ZachBora** [comment]
@Aaron1011 oh right, I remember now skull is a tileentity.

**Comment by Aaron1011** [comment]
@turt2live: Does this look good to merge?

**Comment by turt2live** [comment]
@SpaceManiac looks ready to pull

**Comment by SpaceManiac** [comment]
Merged in a073295a2c8c56c057058f67c4cf2b3d8ada0bbb.

**Pull request closed without merging**
