### PR TITLE
Fix order of FireworkEffect to be inline with NBT values

### PR DESCRIPTION
**Pull request by ZephireNZ**
A small fix in the order of the enum, so that a switch/case is not needed when converting a FireworkEffect Type to NBT and vice versa.

### CODE REVIEW

**Comment by turt2live** [comment]
This has the potential to break plugins.

**Comment by ZephireNZ** [comment]
Good point. Shall I just go with an enum then?

**Comment by turt2live** [comment]
@ZephireNZ as much as it pains me, I'll have to say use an ugly switch in the implementation :(

**Comment by ZephireNZ** [comment]
Alright then. Clunky it is.

**Pull request closed without merging**
