### PR TITLE
Fix facing methods for fence gates

### PR DESCRIPTION
**Pull request by socram8888**
Fix for https://github.com/GlowstoneMC/Glowstone/pull/200#issuecomment-56320882

### CODE REVIEW

**Comment by Tonodus** [comment]
Why did you invert the given direction? That doesn't make that much sense and isn't expected IMO.

**Comment by socram8888** [comment]
GATE_\* were already defined and it's the direction the gate is open/opens to. So if the player is looking at the north BlockFace and interacts with that, the gate doors open to the south.

**Comment by Tonodus** [comment]
I think it's confusing since you'd expect it to set the direction MC use. So if you call that method the same facing direction should be visible when you hover over the gate in MC debug screen.

For fence gates implementation we can easily use getOppositeFace() if we need to do so.

**Comment by SpaceManiac** [comment]
I think I agree with Tonodus here. setFacing() and getFacing() should indicate which direction the fence gate is facing, which is the "outwards" direction, and ought to match what shows up in the F3 menu. The oppositeFace() can easily be done in Glowstone like it is for many other blocks.

**Comment by SpaceManiac** [comment]
Merged at long last, with the changes discussed above, in 54bf87837fafb0b48bac20e6de6dba455d96d10e.

**Pull request closed without merging**
